

export const alumniProfiles = [
    {
      id: 1,
      name: "Ajiboye Opeyemi",
      role: "developer",
      sector: "it",
      roleKey: "roleDeveloper",
      educationKey: "educationPhD",
      experienceKey: "experience10",
      image: "/assets/Marketplace 1.jpg",
    },
    {
      id: 2,
      name: "Daniel Adeniran",
      role: "designer",
      sector: "healthcare",
      roleKey: "roleDesigner",
      educationKey: "educationMSc",
      experienceKey: "experience5",
      image: "/assets/Marketplace 2.jpg",
    },
    {
      id: 3,
      name: "Wale Adedayo",
      role: "developer",
      sector: "finance",
      roleKey: "roleDeveloper",
      educationKey: "educationMSc",
      experienceKey: "experience5",
      image: "/assets/Marketplace 3.jpg",
    },
    {
      id: 4,
      name: "Chioma Okonkwo",
      role: "manager",
      sector: "education",
      roleKey: "roleManager",
      educationKey: "educationMSc",
      experienceKey: "experience5",
      image: "/assets/Marketplace 4.jpg",
    },
    {
      id: 5,
      name: "Ajiboye Opeyemi",
      role: "developer",
      sector: "it",
      roleKey: "roleDeveloper",
      educationKey: "educationPhD",
      experienceKey: "experience10",
      image: "/assets/Marketplace 1.jpg",
    },
    {
      id: 6,
      name: "Daniel Adeniran",
      role: "designer",
      sector: "healthcare",
      roleKey: "roleDesigner",
      educationKey: "educationMSc",
      experienceKey: "experience5",
      image: "/assets/Marketplace 2.jpg",
    },
    {
      id: 7,
      name: "Wale Adedayo",
      role: "developer",
      sector: "finance",
      roleKey: "roleDeveloper",
      educationKey: "educationMSc",
      experienceKey: "experience5",
      image: "/assets/Marketplace 3.jpg",
    },
    {
      id: 8,
      name: "Chioma Okonkwo",
      role: "manager",
      sector: "education",
      roleKey: "roleManager",
      educationKey: "educationMSc",
      experienceKey: "experience5",
      image: "/assets/Marketplace 4.jpg",
    },
  ];

  export const yourEvents = [
  {
    id: 1,
    name: "Lead with a Grounded Confidence in a Changing...",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Leadership Academy",
    attendees: 45,
    cover:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=200&h=200&fit=crop",
    status: "upcoming",
  },
  {
    id: 2,
    name: "Lead with a Grounded Confidence in a Changing...",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Leadership Academy",
    attendees: 32,
    cover:
      "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=200&h=200&fit=crop",
    status: "upcoming",
  },
  {
    id: 3,
    name: "Lead with a Grounded Confidence in a Changing...",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Leadership Academy",
    attendees: 28,
    cover:
      "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=200&h=200&fit=crop",
    status: "upcoming",
  },
  {
    id: 4,
    name: "Tech Innovation Summit 2025",
    date: "Sat, Dec 20, 2025",
    time: "9:00AM",
    organizer: "Tech Africa",
    attendees: 156,
    cover:
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=200&h=200&fit=crop",
    status: "upcoming",
  },
  {
    id: 5,
    name: "Startup Networking Night",
    date: "Mon, Dec 22, 2025",
    time: "6:00PM",
    organizer: "Founders Hub",
    attendees: 89,
    cover:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=200&h=200&fit=crop",
    status: "upcoming",
  },
];

export const allRecommendedEvents = [
  {
    id: 4,
    name: "JSworld Conference Africa - Diversity Focus",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Alphamarine Photography LTD",
    attendees: 1,
    cover:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 5,
    name: "9th Global Summit on Precision Diagnosis and Treatment of Prostate Cancer",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Alphamarine Photography LTD",
    attendees: 1,
    cover:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 6,
    name: "2025 Drive for the Driven Golf Tournament",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Alphamarine Photography LTD",
    attendees: 100,
    cover:
      "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 7,
    name: "JSworld Conference Africa - Diversity Focus",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Alphamarine Photography LTD",
    attendees: 1,
    cover:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 8,
    name: "9th Global Summit on Precision Diagnosis and Treatment of Prostate Cancer",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Alphamarine Photography LTD",
    attendees: 1,
    cover:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 9,
    name: "2025 Drive for the Driven Golf Tournament",
    date: "Fri, Dec 15, 2025",
    time: "7:00PM",
    organizer: "Alphamarine Photography LTD",
    attendees: 100,
    cover:
      "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 10,
    name: "AI & Machine Learning Workshop",
    date: "Sat, Dec 18, 2025",
    time: "10:00AM",
    organizer: "Tech Academy Africa",
    attendees: 75,
    cover:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 11,
    name: "Women in Tech Leadership Summit",
    date: "Wed, Dec 20, 2025",
    time: "9:00AM",
    organizer: "WiT Foundation",
    attendees: 200,
    cover:
      "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400&h=300&fit=crop",
    status: "upcoming",
  },
  {
    id: 12,
    name: "Startup Pitch Night 2025",
    date: "Thu, Dec 21, 2025",
    time: "6:00PM",
    organizer: "Venture Hub Africa",
    attendees: 150,
    cover:
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&h=300&fit=crop",
    status: "upcoming",
  },
];