import { Inter } from "next/font/google";
import ".././globals.css";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  // 1. Await the params before accessing properties
  const { locale } = await params;

  // 2. Now 'locale' will be defined (e.g., "en" or "fr")
  console.log(locale, "locale detected");
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Load messages for this locale so /fr shows French regardless of getRequestConfig
  const messages = (await import(`../../messages/${locale}.json`)).default;
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Toaster position="center" />
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
