import { Inter } from "next/font/google";
import ".././globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
// 1. Await the params before accessing properties
  const { locale } = await params;

  // 2. Now 'locale' will be defined (e.g., "en" or "fr")
  console.log(locale, "locale detected");
if (!routing.locales.includes(locale)) {
    notFound();
  }

  
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>

        <NextIntlClientProvider messages={messages}>

          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
